title: Ankit Prajapati # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Frontend Engineer
  <br><br>
  <a href="mailto:cs.ankitprajapati@gmail.com">cs.ankitprajapati@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/hiankit/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/PrajapatiAnkit">Gihub</a> 
theme: jekyll-theme-minimal
